version: 2
updates:
  # Maven dependencies for server
  - package-ecosystem: "maven"
    directory: "/server"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: "monthly"
    target-branch: "main"
    groups:
      server-dependencies:
        patterns:
          - "*"

  # npm dependencies for client
  - package-ecosystem: "npm"
    directory: "/client"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: "monthly"
    target-branch: "main"
    groups:
      client-dependencies:
        patterns:
          - "*"
